/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sprintplannerjava;

import java.awt.Color;
import java.awt.Component;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guruda
 */
public class chatserver extends javax.swing.JFrame {

    static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    public static List<DataOutputStream> dout = new ArrayList<>();
     /**
     * Creates new form chatserver
     */
    public chatserver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageArea = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        moveButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        highestEstimate = new javax.swing.JTextField();
        showButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEAM DESTINY SPRINT PLANNER ADMIN");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("PUSH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dtm = new DefaultTableModel(0, 0);

        String header[] = new String[] { "Name", "Estimate" };
        dtm.setColumnIdentifiers(header);
        jTable2.setModel(dtm);
        //getContentPane().setBackground(new Color(228, 255, 247));
        jScrollPane3.setViewportView(jTable2);
        jScrollPane3.getViewport().setBackground(Color.WHITE);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(255, 175, 170));

        for (int i = 0; i < jTable2.getModel().getColumnCount(); i++) {
            jTable2.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        moveButton.setBackground(new java.awt.Color(204, 255, 204));
        moveButton.setText("MOVE");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });
        moveButton.setEnabled(false);

        dtm1 = new DefaultTableModel(0, 0);

        String header1[] = new String[] { "JIRA", "Estimate" };
        dtm1.setColumnIdentifiers(header1);
        jTable3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTable3.setModel(dtm1);
        getContentPane().setBackground(Color.WHITE);
        jTable3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable3PropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);
        jScrollPane4.getViewport().setBackground(Color.WHITE);
        DefaultTableCellRenderer headerRenderer1 = new DefaultTableCellRenderer();
        headerRenderer1.setBackground(new Color(255, 175, 170));

        for (int i = 0; i < jTable3.getModel().getColumnCount(); i++) {
            jTable3.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer1);
        }

        highestEstimate.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        highestEstimate.setForeground(new java.awt.Color(0, 153, 153));
        highestEstimate.setBorder(javax.swing.BorderFactory.createTitledBorder("ESTIMATE"));
        highestEstimate.setHorizontalAlignment(JTextField.CENTER);

        showButton.setBackground(new java.awt.Color(204, 255, 255));
        showButton.setText("SHOW");
        showButton.setEnabled(false);
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("TOTAL ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageArea, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveButton)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(highestEstimate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(moveButton)
                    .addComponent(showButton))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(highestEstimate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        valuesList =  new HashMap<String,String>();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String msgout = "";
        msgout = messageArea.getText().trim();
        for(DataOutputStream d:dout){
            try {
                d.writeUTF(msgout);
            } catch (IOException ex) {
                Logger.getLogger(chatserver.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        showButton.setEnabled(true);
        jButton1.setEnabled(false);
        dtm.setRowCount(0);
        valuesList =  new HashMap<String,String>();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        // TODO add your handling code here:
        chatserver.dtm1.addRow(new Object[] { messageArea.getText(),highestEstimate.getText()});
        moveButton.setEnabled(false);
        jButton1.setEnabled(true);
        highestEstimate.setText("");
        highestEstimate.setFocusable(false);
        dtm.setRowCount(0);
        messageArea.setText("");
        messageArea.setFocusable(true);
        computeTotalEstimate();
    }//GEN-LAST:event_moveButtonActionPerformed
    private static void computeTotalEstimate(){
        int total = 0;
        for(int i = 0;i < dtm1.getRowCount();i++){
            total = total + Integer.parseInt(jTable3.getValueAt(i, 1).toString());
        }
        jTextField1.setText(Integer.toString(total));
        jTextField1.setFocusable(false);
    }
    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        showButton.setEnabled(false);
        moveButton.setEnabled(true);
        chatserver.highestEstimate.setText(Integer.toString(chatserver.estimateValue));
        chatserver.dtm.setRowCount(0);
                        for (Map.Entry<String,String> entry : chatserver.valuesList.entrySet())
                            chatserver.dtm.addRow(new Object[] {entry.getKey(),entry.getValue()});
                 
    }//GEN-LAST:event_showButtonActionPerformed

    private void jTable3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable3PropertyChange
         
    }//GEN-LAST:event_jTable3PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chatserver().setVisible(true);
            }
        });
        
        String msgin = "";
        ss = new ServerSocket(1201);
        while(true){
            System.out.println("Connected");
            s = ss.accept();
            System.out.println("Connected1");
            new EchoThread(s).start();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField highestEstimate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable3;
    private static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField messageArea;
    public static javax.swing.JButton moveButton;
    public static javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
    public static DefaultTableModel dtm;
    public static DefaultTableModel dtm1;
    public static Map<String,String> valuesList;
    public static int estimateValue;
}
